default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres

development:
  <<: *default
  database: one_bit_secret_friend_development
test:
  <<: *default
  database: one_bit_secret_friend_test

production:
  <<: *default
  database: one_bit_secret_friend_production
